[package]
name = "kelake-dom"
version = "0.1.0"
authors = ["laopo001 <353272497@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# [lib]
# crate-type = ["cdylib"]

[dependencies]
kelake = {path = "../kelake"}
wasm-bindgen = "0.2.69"

[dependencies.web-sys]
version = "0.3.46"
features = [
  'Document',
  'Element',
  'HtmlElement',
  'Node',
  'Window',
]